package proxies.ext.taxComputer;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.1
 * 2013-10-21T00:05:22.084+02:00
 * Generated source version: 2.5.1
 * 
 */
@WebService(targetNamespace = "http://external/", name = "TaxComputer")
@XmlSeeAlso({ObjectFactory.class})
public interface TaxComputer {

    @WebResult(name = "simple_result", targetNamespace = "")
    @RequestWrapper(localName = "simple", targetNamespace = "http://external/", className = "proxies.ext.taxComputer.Simple")
    @WebMethod
    @ResponseWrapper(localName = "simpleResponse", targetNamespace = "http://external/", className = "proxies.ext.taxComputer.SimpleResponse")
    public proxies.ext.taxComputer.TaxComputation simple(
        @WebParam(name = "simpleTaxInfo", targetNamespace = "")
        proxies.ext.taxComputer.SimpleTaxRequest simpleTaxInfo
    );

    @WebResult(name = "complex_result", targetNamespace = "")
    @RequestWrapper(localName = "complex", targetNamespace = "http://external/", className = "proxies.ext.taxComputer.Complex")
    @WebMethod
    @ResponseWrapper(localName = "complexResponse", targetNamespace = "http://external/", className = "proxies.ext.taxComputer.ComplexResponse")
    public proxies.ext.taxComputer.TaxComputation complex(
        @WebParam(name = "complexTaxInfo", targetNamespace = "")
        proxies.ext.taxComputer.AdvancedTaxRequest complexTaxInfo
    );
}
