package proxies.ext.taxComputer;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.5.1
 * 2013-10-21T00:05:22.092+02:00
 * Generated source version: 2.5.1
 * 
 */
@WebServiceClient(name = "TaxComputerService", 
                  wsdlLocation = "file:/Users/mosser/MuleStudio/workspace/soa1_bus_demo/src/main/resources/tax_computer.wsdl",
                  targetNamespace = "http://external/") 
public class TaxComputerService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://external/", "TaxComputerService");
    public final static QName TaxComputerPort = new QName("http://external/", "TaxComputerPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/Users/mosser/MuleStudio/workspace/soa1_bus_demo/src/main/resources/tax_computer.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(TaxComputerService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/Users/mosser/MuleStudio/workspace/soa1_bus_demo/src/main/resources/tax_computer.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public TaxComputerService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public TaxComputerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TaxComputerService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns TaxComputer
     */
    @WebEndpoint(name = "TaxComputerPort")
    public TaxComputer getTaxComputerPort() {
        return super.getPort(TaxComputerPort, TaxComputer.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TaxComputer
     */
    @WebEndpoint(name = "TaxComputerPort")
    public TaxComputer getTaxComputerPort(WebServiceFeature... features) {
        return super.getPort(TaxComputerPort, TaxComputer.class, features);
    }

}
