package proxies.ext.idgen;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.1
 * 2013-10-21T00:05:09.117+02:00
 * Generated source version: 2.5.1
 * 
 */
@WebService(targetNamespace = "http://external/", name = "AnonymousIdentifier")
@XmlSeeAlso({ObjectFactory.class})
public interface AnonymousIdentifier {

    @WebResult(name = "identifier", targetNamespace = "")
    @RequestWrapper(localName = "build", targetNamespace = "http://external/", className = "proxies.ext.idgen.Build")
    @WebMethod
    @ResponseWrapper(localName = "buildResponse", targetNamespace = "http://external/", className = "proxies.ext.idgen.BuildResponse")
    public java.lang.String build();
}
