package proxies.ext.idgen;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.5.1
 * 2013-10-21T00:05:09.124+02:00
 * Generated source version: 2.5.1
 * 
 */
@WebServiceClient(name = "IdentifierGeneratorService", 
                  wsdlLocation = "file:/Users/mosser/MuleStudio/workspace/soa1_bus_demo/src/main/resources/idGen.wsdl",
                  targetNamespace = "http://external/") 
public class IdentifierGeneratorService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://external/", "IdentifierGeneratorService");
    public final static QName AnonymousIdentifierPort = new QName("http://external/", "AnonymousIdentifierPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/Users/mosser/MuleStudio/workspace/soa1_bus_demo/src/main/resources/idGen.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(IdentifierGeneratorService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/Users/mosser/MuleStudio/workspace/soa1_bus_demo/src/main/resources/idGen.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public IdentifierGeneratorService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public IdentifierGeneratorService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IdentifierGeneratorService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns AnonymousIdentifier
     */
    @WebEndpoint(name = "AnonymousIdentifierPort")
    public AnonymousIdentifier getAnonymousIdentifierPort() {
        return super.getPort(AnonymousIdentifierPort, AnonymousIdentifier.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AnonymousIdentifier
     */
    @WebEndpoint(name = "AnonymousIdentifierPort")
    public AnonymousIdentifier getAnonymousIdentifierPort(WebServiceFeature... features) {
        return super.getPort(AnonymousIdentifierPort, AnonymousIdentifier.class, features);
    }

}
